import manifest from './visuals-manifest.json';

export type GalleryImageVariant = { w: number; avifUrl: string; webpUrl: string };

export type GalleryImageExif = {
  camera: string | null;
  lens: string | null;
  aperture: string | null;
  shutterSpeed: string | null;
  iso: string | null;
  focalLength: string | null;
};

export type GalleryImagePack = {
  id: string;
  uploadedAt: string;
  width: number;
  height: number;
  lqip: string;
  variants: GalleryImageVariant[];
  exif?: GalleryImageExif | null;
};

export type PublicGalleryImageMeta = {
  width: number;
  height: number;
  lqip: string;
  variants: { w: number; avif: string; webp: string }[];
  exif?: GalleryImageExif | null;
};

export type PublicGalleryItem =
  | { kind: 'media'; url: string; packId?: string; image?: PublicGalleryImageMeta }
  | { kind: 'youtube'; videoId: string; title?: string; description?: string; embeddable?: boolean }
  | { kind: 'vimeo'; videoId: string };

/**
 * Static YouTube/Vimeo embeds for the gallery (recovered from the old Blob-backed admin panel).
 * `embeddable: false` is for videos whose publisher (e.g. a music rights holder via Content ID)
 * blocks third-party embedding — those open directly on youtube.com instead of trying to play inline.
 */
const EMBEDS: { provider: 'youtube' | 'vimeo'; videoId: string; addedAt: string; embeddable?: boolean }[] = [
  { provider: 'youtube', videoId: 'xhtXOz1Sst0', addedAt: '2026-06-25T06:51:24.403Z' },
  { provider: 'youtube', videoId: 'q3UMWIFAyQE', addedAt: '2026-06-25T06:48:36.597Z' },
  { provider: 'youtube', videoId: 'sZImzEHTLes', addedAt: '2026-06-25T06:48:00.450Z', embeddable: false },
  { provider: 'youtube', videoId: 's4uXQo1exKs', addedAt: '2026-06-25T06:46:02.705Z' },
];

function readYoutubeApiKey(): string | undefined {
  const fromMeta = (import.meta.env as Record<string, string | undefined>).YOUTUBE_API_KEY;
  if (fromMeta) return fromMeta;
  if (typeof process !== 'undefined') return process.env.YOUTUBE_API_KEY;
  return undefined;
}

async function fetchYoutubeSnippet(videoId: string): Promise<{ title: string; description: string } | null> {
  const apiKey = readYoutubeApiKey();
  if (!apiKey) return null;
  try {
    const res = await fetch(
      `https://www.googleapis.com/youtube/v3/videos?part=snippet&id=${encodeURIComponent(videoId)}&key=${apiKey}`,
    );
    if (!res.ok) return null;
    const json = (await res.json()) as { items?: { snippet?: { title?: string; description?: string } }[] };
    const snippet = json.items?.[0]?.snippet;
    if (!snippet) return null;
    return { title: snippet.title ?? '', description: snippet.description ?? '' };
  } catch {
    return null;
  }
}

const packs = (manifest as { packs: GalleryImagePack[] }).packs;

function packToPublicItem(p: GalleryImagePack): PublicGalleryItem {
  const largest = p.variants[p.variants.length - 1]!;
  return {
    kind: 'media',
    url: largest.webpUrl,
    packId: p.id,
    image: {
      width: p.width,
      height: p.height,
      lqip: p.lqip,
      variants: p.variants.map((v) => ({ w: v.w, avif: v.avifUrl, webp: v.webpUrl })),
      exif: p.exif ?? null,
    },
  };
}

/**
 * Static gallery sourced from public/media/visuals (generated by scripts/build-visuals-manifest.mjs)
 * plus EMBEDS. YouTube title/description are fetched once at build time (this page is prerendered)
 * via the YouTube Data API; silently omitted if YOUTUBE_API_KEY isn't configured.
 */
export async function resolveGalleryItems(): Promise<PublicGalleryItem[]> {
  const sortedEmbeds = [...EMBEDS].sort((a, b) => new Date(b.addedAt).getTime() - new Date(a.addedAt).getTime());

  const embedItems: PublicGalleryItem[] = await Promise.all(
    sortedEmbeds.map(async (e): Promise<PublicGalleryItem> => {
      if (e.provider !== 'youtube') return { kind: 'vimeo', videoId: e.videoId };
      const snippet = await fetchYoutubeSnippet(e.videoId);
      return {
        kind: 'youtube',
        videoId: e.videoId,
        ...(snippet?.title ? { title: snippet.title } : {}),
        ...(snippet?.description ? { description: snippet.description } : {}),
        ...(e.embeddable === false ? { embeddable: false } : {}),
      };
    }),
  );

  return [...packs.map(packToPublicItem), ...embedItems];
}
