import manifest from './visuals-manifest.json';

export type GalleryImageVariant = { w: number; avifUrl: string; webpUrl: string };

export type GalleryImageExif = {
  camera: string | null;
  lens: string | null;
  aperture: string | null;
  shutterSpeed: string | null;
  iso: string | null;
  focalLength: string | null;
};

export type GalleryImagePack = {
  id: string;
  uploadedAt: string;
  width: number;
  height: number;
  lqip: string;
  variants: GalleryImageVariant[];
  exif?: GalleryImageExif | null;
};

export type PublicGalleryImageMeta = {
  width: number;
  height: number;
  lqip: string;
  variants: { w: number; avif: string; webp: string }[];
  exif?: GalleryImageExif | null;
};

export type PublicGalleryItem =
  | { kind: 'media'; url: string; packId?: string; image?: PublicGalleryImageMeta }
  | { kind: 'youtube'; videoId: string }
  | { kind: 'vimeo'; videoId: string };

/** Static YouTube/Vimeo embeds for the gallery (recovered from the old Blob-backed admin panel). */
const EMBEDS: { provider: 'youtube' | 'vimeo'; videoId: string; addedAt: string }[] = [
  { provider: 'youtube', videoId: 'xhtXOz1Sst0', addedAt: '2026-06-25T06:51:24.403Z' },
  { provider: 'youtube', videoId: 'q3UMWIFAyQE', addedAt: '2026-06-25T06:48:36.597Z' },
  { provider: 'youtube', videoId: 'sZImzEHTLes', addedAt: '2026-06-25T06:48:00.450Z' },
  { provider: 'youtube', videoId: 's4uXQo1exKs', addedAt: '2026-06-25T06:46:02.705Z' },
];

const packs = (manifest as { packs: GalleryImagePack[] }).packs;

function packToPublicItem(p: GalleryImagePack): PublicGalleryItem {
  const largest = p.variants[p.variants.length - 1]!;
  return {
    kind: 'media',
    url: largest.webpUrl,
    packId: p.id,
    image: {
      width: p.width,
      height: p.height,
      lqip: p.lqip,
      variants: p.variants.map((v) => ({ w: v.w, avif: v.avifUrl, webp: v.webpUrl })),
      exif: p.exif ?? null,
    },
  };
}

/** Static gallery sourced from public/media/visuals (generated by scripts/build-visuals-manifest.mjs) plus EMBEDS. */
export function resolveGalleryItems(): PublicGalleryItem[] {
  const embedItems: PublicGalleryItem[] = [...EMBEDS]
    .sort((a, b) => new Date(b.addedAt).getTime() - new Date(a.addedAt).getTime())
    .map((e) => ({ kind: e.provider, videoId: e.videoId }));
  return [...packs.map(packToPublicItem), ...embedItems];
}
