import manifest from './visuals-manifest.json';

export type GalleryImageVariant = { w: number; avifUrl: string; webpUrl: string };

export type GalleryImagePack = {
  id: string;
  uploadedAt: string;
  width: number;
  height: number;
  lqip: string;
  variants: GalleryImageVariant[];
};

export type PublicGalleryImageMeta = {
  width: number;
  height: number;
  lqip: string;
  variants: { w: number; avif: string; webp: string }[];
};

export type PublicGalleryItem = { kind: 'media'; url: string; packId?: string; image?: PublicGalleryImageMeta };

const packs = (manifest as { packs: GalleryImagePack[] }).packs;

function packToPublicItem(p: GalleryImagePack): PublicGalleryItem {
  const largest = p.variants[p.variants.length - 1]!;
  return {
    kind: 'media',
    url: largest.webpUrl,
    packId: p.id,
    image: {
      width: p.width,
      height: p.height,
      lqip: p.lqip,
      variants: p.variants.map((v) => ({ w: v.w, avif: v.avifUrl, webp: v.webpUrl })),
    },
  };
}

/** Static gallery sourced from public/media/visuals (generated by scripts/build-visuals-manifest.mjs). */
export function resolveGalleryItems(): PublicGalleryItem[] {
  return packs.map(packToPublicItem);
}
